---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - homebrew
    - homebrew-cask
    - java
- hosts: osx
  connection: ssh
  gather_facts: no
  become: no
  roles:
    - homebrew
    - homebrew-cask
    - java