---
- name: Create dotfiles directory
  file:
    path: "{{ dotfiles_path }}"
    state: directory

- name: Clone dotfiles
  git:
    repo: "{{ dotfiles_url }}"
    dest: "{{ dotfiles_path }}"

- name: Bootstrap dotfiles
  shell: "{{ dotfiles_path }}/bootstrap.sh -f"

- name: Setup OSX Defaults
  shell: ~/.osx
