---
 - name: Check homebrew installed or not
   command: "[ -e /usr/local/bin/brew ]"
   register: homebrew_installed
   ignore_errors: yes

 - name: Installing homebrew
   raw: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   when: homebrew_installed|failed

 - name: Update and Upgrade all
   homebrew:
     update_homebrew: yes
     upgrade_all: yes

 - name: brew tap
   homebrew_tap:
     tap: "{{ item }}"
     state: present
   with_items: "{{homebrew_taps}}"

 - name: Install packages
   homebrew:
     name: "{{ item.name }}"
     state: latest
     install_options: "{{ item.install_options|default() }}"
   with_items: "{{homebrew_packages}}"
