---
- name: "Install jenv"
  homebrew: name=jenv state=present

- name: "Install JDKs"
  homebrew_cask: name={{ item }} state=present
  with_items: jdks

- name: "Install Maven"
  homebrew: name=maven state=present

- name: "Install Gradle"
  homebrew: name=gradle state=present
