---
- name: "Get available JDKs"
  shell: "ls /Library/Java/JavaVirtualMachines/"
  register: jvms
  ignore_errors: yes
  changed_when: False

- name: "Register JDKs"
  shell: "jenv add /Library/Java/JavaVirtualMachines/{{ item }}/Contents/Home || true"
  with_items: jvms.stdout_lines
  ignore_errors: yes
  register: result
  changed_when: "'already' not in result.stdout"

- name: "Installs shims for all JDKs"
  shell: "jenv rehash"
  changed_when: False

- name: "Configure jenv maven plugin"
  shell: "jenv enable-plugin maven"
  changed_when: False

- name: "Configure jenv ant plugin"
  shell: "jenv enable-plugin ant"
  changed_when: False

- name: "Configure jenv sbt plugin"
  shell: "jenv enable-plugin sbt"
  changed_when: False

###############################################################
# See https://github.com/ansible/ansible/issues/13872
###############################################################

- lineinfile: dest=/etc/shells line=/usr/local/bin/bash

# Now, we want to set bash4 as the default shell, unless it is already the default
# one.
- name: Make BASH 4 default
  shell:  chsh -s /usr/local/bin/bash